### ISSUE TITLE
Module layout

### ISSUE THREAD

**Issue by dqu123** [ASCIT/donut#18]
@dkong1796 I had a few questions about module design: 
Should we have a module for directory_search and one for ascit_positions / positions ?
Also I noticed Ruddock has both an account module and an auth module.
Should we separate account creation and authentication into two different modules? (Currently we have both in our auth module).

This would allow @ChingYunH and @ootks to split that work (since they both expressed interest in working on authentication / account creation and that's the main backend feature we can implement right now).

**Comment by allisonkong** [comment]
Yeah, they certainly could be combined into a single module (probably called "account", since that's more comprehensive). The account module on ruddock is also missing some important features, such as a page that allows you to change your password, and I had planned on adding email list subscriptions as another feature at some point. So yes, I think the auth module could be a subset of the account module, but probably not the other way around.

**Comment by dqu123** [comment]
Any thoughts @ChingYunH, and @ootks?
One account module seems fine to me.
